# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: npm
    # Look for `package.json` and `lock` files in the `root` directory
    directory: /
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: daily
    open-pull-requests-limit: 30
    labels:
      - npm
    ignore:
      - dependency-name: "proxmox-api"

  - package-ecosystem: github-actions
    open-pull-requests-limit: 30
    directory: /
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: daily
    labels:
      - github-actions